[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
legwork = "86V9Vw6jPnoy4R6feJK6atwMK3x1oUootvvbqb8iZHD6"

[programs.localnet]
legwork = "86V9Vw6jPnoy4R6feJK6atwMK3x1oUootvvbqb8iZHD6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/keys/authority.json"

[scripts]
test = "echo 'tests run through verifier/tests (python) against devnet'"
